language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm-nightly

install:
    - composer install
    - travis/install-nginx.sh
    - travis/install-nginx-setup.sh

script:
    - curl 'http://garden-http.dev/hello.json'
    - phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

addons:
    hosts:
        - garden-http.dev

#before_script:
#    - mysql -uroot -e 'create database if not exists phpunit_garden;'

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    hipchat:
        rooms:
            secure: JQ9QA+PYliSPPxYZ89/SDLOgR0ePGMrJJkaxlP8AqViE0M3zeqmFBvW2zj1CdAl2fXFLrTWu6CFm4KzX66gM9KKmW97TUwGtgapbs3m6OT8zg2yn8jmTseUKB9Sovdo7BzyCKpsJld70tfltk9GWrngqJYww35jWsyhZf7ER4Pw=
    template:
        - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true
    slack:
        secure: ynpl6cvDaoB1jWNtT6buzX/TJNSVomV6uqVV8iEKj0EwRD4eueDy/MyiGDifg4qpWtlEPuXPVdBQMi4jc3JrJP81VumrPv5QCAf3Z3Yl2UhC8LGWJndwj1tWQwXzjAzZExA+6/wScNFDU7VEHkKxbzbkCLO5fh5WL5tFeSUPx9Q=
