language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm-nightly

install:
    - composer install
    - travis/install-nginx.sh
    - travis/install-nginx-setup.sh

script:
    - curl 'http://garden-http.dev/hello.json'
    - phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

addons:
    hosts:
        - garden-http.dev

#before_script:
#    - mysql -uroot -e 'create database if not exists phpunit_garden;'

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    hipchat:
        rooms:
            - zdxegI0dfQAmrnfzKg303gZ3Y3PINqydisusLfF8lVud7+XRSbKslc99T2kmSMGZF4lrQ9L/+uhCU+M8I0OrnNTxDfA6in+TDpi4i5FJasVRUKb9LAWhncLV0n3232IwozXLC2uJlbDlNPkW0rO+z+7885GAy4WTYf568pg4cUA=
        template:
             - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
        notify: true
