language: php

php:
#    - 5.4
    - 5.5
#    - 5.6
#    - hhvm
#    - hhvm-nightly

matrix:
    fast_finish: true
#    allow_failures:
#        - php: hhvm-nightly

install:
    - travis/install.sh
    - composer install

script:
    - curl 'http://garden-http.dev/hello.json'
    - phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

addons:
  hosts:
    - garden-http.dev

#before_script:
#    - mysql -uroot -e 'create database if not exists phpunit_garden;'

#after_script:
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
