language: php

php:
    - 5.6
    - 7.0
    - hhvm

dist: xenial

sudo: false

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true

install:
    - composer install
    - composer require phpunit/phpunit ~5
    - travis/install-nginx.sh

script:
    - curl -vsf 'http://garden-http.dev:8080/hello.json' &> /dev/stdout
    - ./vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

addons:
    apt:
      packages:
        - nginx
        - realpath
    hosts:
        - garden-http.dev

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    slack:
        secure: ynpl6cvDaoB1jWNtT6buzX/TJNSVomV6uqVV8iEKj0EwRD4eueDy/MyiGDifg4qpWtlEPuXPVdBQMi4jc3JrJP81VumrPv5QCAf3Z3Yl2UhC8LGWJndwj1tWQwXzjAzZExA+6/wScNFDU7VEHkKxbzbkCLO5fh5WL5tFeSUPx9Q=
